### ISSUE TITLE
run in browser

### ISSUE THREAD

**Issue by kiwiidb** [ShahanaFarooqui/CLN-Commando-Client#1]
Is it possible to run this in the browser?

**Comment by ShahanaFarooqui** [comment]
Sorry but I did not try to run it in the browser because that was not my requirement. 
I will try to test it in the browser whenever I work on it next time. But, I do not have any plan to do that in near future.

**Comment by lnbc1QWFyb24** [comment]
Hey @kiwiidb I have been working on a browser version of this which you can [check out here](https://github.com/aaronbarnardsound/lnmessage).
